export const staticSankeyData = {
  "totalDataNumber": 15338,
  "totalNodeNumber": {
    "DESKTOP-1VDHKFU": 14420,
    "DESKTOP-5NVMPM1": 918,
    "Application Hang": 7,
    "Application Popup": 7,
    "BTHUSB": 268,
    "Desktop Window Manager": 11,
    "Disk": 11,
    "Dolby DAX3": 2,
    "ESENT": 487,
    "EventLog": 264,
    "IntelDalJhi": 1,
    "MEIx64": 56,
    "Microsoft-Windows-DHCPv6-Client": 160,
    "Microsoft-Windows-DNS-Client": 131,
    "Microsoft-Windows-Defrag": 1,
    "Microsoft-Windows-Dhcp-Client": 44,
    "Microsoft-Windows-Diagnostics-Networking": 1,
    "Microsoft-Windows-Directory-Services-SAM": 8,
    "Microsoft-Windows-DistributedCOM": 184,
    "Microsoft-Windows-DriverFrameworks-UserMode": 28,
    "Microsoft-Windows-Eventlog": 7,
    "Microsoft-Windows-FilterManager": 99,
    "Microsoft-Windows-GroupPolicy": 1,
    "Microsoft-Windows-Kernel-Boot": 150,
    "Microsoft-Windows-Kernel-General": 440,
    "Microsoft-Windows-Kernel-PnP": 12,
    "Microsoft-Windows-Kernel-Power": 403,
    "Microsoft-Windows-Kernel-Processor-Power": 132,
    "Microsoft-Windows-NDIS": 1,
    "Microsoft-Windows-Ntfs": 52,
    "Microsoft-Windows-Power-Troubleshooter": 47,
    "Microsoft-Windows-Security-Auditing": 10116,
    "Microsoft-Windows-Security-SPP": 71,
    "Microsoft-Windows-Sysmon": 772,
    "Microsoft-Windows-TPM-WMI": 18,
    "Microsoft-Windows-Time-Service": 127,
    "Microsoft-Windows-UserModePowerService": 36,
    "Microsoft-Windows-UserPnp": 34,
    "Microsoft-Windows-WLAN-AutoConfig": 23,
    "Microsoft-Windows-WPDClassInstaller": 13,
    "Microsoft-Windows-Windows Defender": 396,
    "Microsoft-Windows-WindowsUpdateClient": 389,
    "Microsoft-Windows-Wininit": 13,
    "Microsoft-Windows-Winlogon": 29,
    "MySQL": 7,
    "SecurityCenter": 8,
    "Service Control Manager": 153,
    "SpeechRuntime": 19,
    "System Restore": 1,
    "Tcpip": 7,
    "User32": 10,
    "VSS": 4,
    "Virtual Disk Service": 1,
    "Win32k": 34,
    "Windows Error Reporting": 11,
    "igfxCUIService2.0.0.0": 4,
    ".NET Runtime": 2,
    "AdobeARMservice": 8,
    "Application Error": 4,
    "Display": 1,
    "错误": 259,
    "信息": 14721,
    "警告": 344,
    "Information": 14
  },
  "flowData": {
    "nodes": [{
      "name": "DESKTOP-1VDHKFU"
    }, {
      "name": "Application Hang"
    }, {
      "name": "错误"
    }, {
      "name": "Application Popup"
    }, {
      "name": "信息"
    }, {
      "name": "BTHUSB"
    }, {
      "name": "警告"
    }, {
      "name": "Desktop Window Manager"
    }, {
      "name": "Disk"
    }, {
      "name": "Dolby DAX3"
    }, {
      "name": "Information"
    }, {
      "name": "ESENT"
    }, {
      "name": "EventLog"
    }, {
      "name": "IntelDalJhi"
    }, {
      "name": "MEIx64"
    }, {
      "name": "Microsoft-Windows-DHCPv6-Client"
    }, {
      "name": "Microsoft-Windows-DNS-Client"
    }, {
      "name": "Microsoft-Windows-Defrag"
    }, {
      "name": "Microsoft-Windows-Dhcp-Client"
    }, {
      "name": "Microsoft-Windows-Diagnostics-Networking"
    }, {
      "name": "Microsoft-Windows-Directory-Services-SAM"
    }, {
      "name": "Microsoft-Windows-DistributedCOM"
    }, {
      "name": "Microsoft-Windows-DriverFrameworks-UserMode"
    }, {
      "name": "Microsoft-Windows-Eventlog"
    }, {
      "name": "Microsoft-Windows-FilterManager"
    }, {
      "name": "Microsoft-Windows-GroupPolicy"
    }, {
      "name": "Microsoft-Windows-Kernel-Boot"
    }, {
      "name": "Microsoft-Windows-Kernel-General"
    }, {
      "name": "Microsoft-Windows-Kernel-PnP"
    }, {
      "name": "Microsoft-Windows-Kernel-Power"
    }, {
      "name": "Microsoft-Windows-Kernel-Processor-Power"
    }, {
      "name": "Microsoft-Windows-NDIS"
    }, {
      "name": "Microsoft-Windows-Ntfs"
    }, {
      "name": "Microsoft-Windows-Power-Troubleshooter"
    }, {
      "name": "Microsoft-Windows-Security-Auditing"
    }, {
      "name": "Microsoft-Windows-Security-SPP"
    }, {
      "name": "Microsoft-Windows-Sysmon"
    }, {
      "name": "Microsoft-Windows-TPM-WMI"
    }, {
      "name": "Microsoft-Windows-Time-Service"
    }, {
      "name": "Microsoft-Windows-UserModePowerService"
    }, {
      "name": "Microsoft-Windows-UserPnp"
    }, {
      "name": "Microsoft-Windows-WLAN-AutoConfig"
    }, {
      "name": "Microsoft-Windows-WPDClassInstaller"
    }, {
      "name": "Microsoft-Windows-Windows Defender"
    }, {
      "name": "Microsoft-Windows-WindowsUpdateClient"
    }, {
      "name": "Microsoft-Windows-Wininit"
    }, {
      "name": "Microsoft-Windows-Winlogon"
    }, {
      "name": "MySQL"
    }, {
      "name": "SecurityCenter"
    }, {
      "name": "Service Control Manager"
    }, {
      "name": "SpeechRuntime"
    }, {
      "name": "System Restore"
    }, {
      "name": "Tcpip"
    }, {
      "name": "User32"
    }, {
      "name": "VSS"
    }, {
      "name": "Virtual Disk Service"
    }, {
      "name": "Win32k"
    }, {
      "name": "Windows Error Reporting"
    }, {
      "name": "igfxCUIService2.0.0.0"
    }, {
      "name": "DESKTOP-5NVMPM1"
    }, {
      "name": ".NET Runtime"
    }, {
      "name": "AdobeARMservice"
    }, {
      "name": "Application Error"
    }, {
      "name": "Display"
    }, {
      "name": "ListenService"
    }],
    "links": [{
      "source": "DESKTOP-1VDHKFU",
      "target": "Application Hang",
      "value": 7
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "Application Popup",
      "value": 2
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "BTHUSB",
      "value": 193
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "Desktop Window Manager",
      "value": 3
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "Disk",
      "value": 4
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "Dolby DAX3",
      "value": 2
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "ESENT",
      "value": 71
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "EventLog",
      "value": 61
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "IntelDalJhi",
      "value": 1
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "MEIx64",
      "value": 14
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "Microsoft-Windows-DHCPv6-Client",
      "value": 25
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "Microsoft-Windows-DNS-Client",
      "value": 131
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "Microsoft-Windows-Defrag",
      "value": 1
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "Microsoft-Windows-Dhcp-Client",
      "value": 44
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "Microsoft-Windows-Diagnostics-Networking",
      "value": 1
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "Microsoft-Windows-Directory-Services-SAM",
      "value": 8
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "Microsoft-Windows-DistributedCOM",
      "value": 184
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "Microsoft-Windows-DriverFrameworks-UserMode",
      "value": 28
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "Microsoft-Windows-Eventlog",
      "value": 7
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "Microsoft-Windows-FilterManager",
      "value": 99
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "Microsoft-Windows-GroupPolicy",
      "value": 1
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "Microsoft-Windows-Kernel-Boot",
      "value": 150
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "Microsoft-Windows-Kernel-General",
      "value": 440
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "Microsoft-Windows-Kernel-PnP",
      "value": 12
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "Microsoft-Windows-Kernel-Power",
      "value": 403
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "Microsoft-Windows-Kernel-Processor-Power",
      "value": 132
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "Microsoft-Windows-NDIS",
      "value": 1
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "Microsoft-Windows-Ntfs",
      "value": 52
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "Microsoft-Windows-Power-Troubleshooter",
      "value": 47
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "Microsoft-Windows-Security-Auditing",
      "value": 10116
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "Microsoft-Windows-Security-SPP",
      "value": 71
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "Microsoft-Windows-Sysmon",
      "value": 772
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "Microsoft-Windows-TPM-WMI",
      "value": 18
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "Microsoft-Windows-Time-Service",
      "value": 127
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "Microsoft-Windows-UserModePowerService",
      "value": 36
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "Microsoft-Windows-UserPnp",
      "value": 34
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "Microsoft-Windows-WLAN-AutoConfig",
      "value": 23
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "Microsoft-Windows-WPDClassInstaller",
      "value": 13
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "Microsoft-Windows-Windows Defender",
      "value": 396
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "Microsoft-Windows-WindowsUpdateClient",
      "value": 389
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "Microsoft-Windows-Wininit",
      "value": 13
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "Microsoft-Windows-Winlogon",
      "value": 29
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "MySQL",
      "value": 7
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "SecurityCenter",
      "value": 8
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "Service Control Manager",
      "value": 153
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "SpeechRuntime",
      "value": 19
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "System Restore",
      "value": 1
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "Tcpip",
      "value": 7
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "User32",
      "value": 10
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "VSS",
      "value": 4
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "Virtual Disk Service",
      "value": 1
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "Win32k",
      "value": 34
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "Windows Error Reporting",
      "value": 11
    }, {
      "source": "DESKTOP-1VDHKFU",
      "target": "igfxCUIService2.0.0.0",
      "value": 4
    }, {
      "source": "DESKTOP-5NVMPM1",
      "target": ".NET Runtime",
      "value": 2
    }, {
      "source": "DESKTOP-5NVMPM1",
      "target": "AdobeARMservice",
      "value": 8
    }, {
      "source": "DESKTOP-5NVMPM1",
      "target": "Application Error",
      "value": 4
    }, {
      "source": "DESKTOP-5NVMPM1",
      "target": "Application Popup",
      "value": 5
    }, {
      "source": "DESKTOP-5NVMPM1",
      "target": "BTHUSB",
      "value": 75
    }, {
      "source": "DESKTOP-5NVMPM1",
      "target": "Desktop Window Manager",
      "value": 8
    }, {
      "source": "DESKTOP-5NVMPM1",
      "target": "Disk",
      "value": 7
    }, {
      "source": "DESKTOP-5NVMPM1",
      "target": "Display",
      "value": 1
    }, {
      "source": "DESKTOP-5NVMPM1",
      "target": "ESENT",
      "value": 416
    }, {
      "source": "DESKTOP-5NVMPM1",
      "target": "EventLog",
      "value": 203
    }, {
      "source": "DESKTOP-5NVMPM1",
      "target": "ListenService",
      "value": 12
    }, {
      "source": "DESKTOP-5NVMPM1",
      "target": "MEIx64",
      "value": 42
    }, {
      "source": "DESKTOP-5NVMPM1",
      "target": "Microsoft-Windows-DHCPv6-Client",
      "value": 135
    }, {
      "source": "Application Hang",
      "target": "错误",
      "value": 7
    }, {
      "source": "Application Popup",
      "target": "信息",
      "value": 7
    }, {
      "source": "BTHUSB",
      "target": "信息",
      "value": 160
    }, {
      "source": "BTHUSB",
      "target": "警告",
      "value": 92
    }, {
      "source": "Desktop Window Manager",
      "target": "信息",
      "value": 11
    }, {
      "source": "Disk",
      "target": "警告",
      "value": 7
    }, {
      "source": "Disk",
      "target": "错误",
      "value": 4
    }, {
      "source": "Dolby DAX3",
      "target": "Information",
      "value": 2
    }, {
      "source": "ESENT",
      "target": "信息",
      "value": 487
    }, {
      "source": "EventLog",
      "target": "信息",
      "value": 258
    }, {
      "source": "EventLog",
      "target": "错误",
      "value": 6
    }, {
      "source": "IntelDalJhi",
      "target": "信息",
      "value": 1
    }, {
      "source": "MEIx64",
      "target": "信息",
      "value": 55
    }, {
      "source": "MEIx64",
      "target": "警告",
      "value": 1
    }, {
      "source": "Microsoft-Windows-DHCPv6-Client",
      "target": "信息",
      "value": 160
    }, {
      "source": "Microsoft-Windows-DNS-Client",
      "target": "警告",
      "value": 131
    }, {
      "source": "Microsoft-Windows-Defrag",
      "target": "信息",
      "value": 1
    }, {
      "source": "Microsoft-Windows-Dhcp-Client",
      "target": "信息",
      "value": 44
    }, {
      "source": "Microsoft-Windows-Diagnostics-Networking",
      "target": "信息",
      "value": 1
    }, {
      "source": "Microsoft-Windows-Directory-Services-SAM",
      "target": "信息",
      "value": 8
    }, {
      "source": "Microsoft-Windows-DistributedCOM",
      "target": "错误",
      "value": 184
    }, {
      "source": "Microsoft-Windows-DriverFrameworks-UserMode",
      "target": "信息",
      "value": 28
    }, {
      "source": "Microsoft-Windows-Eventlog",
      "target": "信息",
      "value": 7
    }, {
      "source": "Microsoft-Windows-FilterManager",
      "target": "信息",
      "value": 99
    }, {
      "source": "Microsoft-Windows-GroupPolicy",
      "target": "信息",
      "value": 1
    }, {
      "source": "Microsoft-Windows-Kernel-Boot",
      "target": "信息",
      "value": 150
    }, {
      "source": "Microsoft-Windows-Kernel-General",
      "target": "信息",
      "value": 440
    }, {
      "source": "Microsoft-Windows-Kernel-PnP",
      "target": "警告",
      "value": 12
    }, {
      "source": "Microsoft-Windows-Kernel-Power",
      "target": "信息",
      "value": 403
    }, {
      "source": "Microsoft-Windows-Kernel-Processor-Power",
      "target": "信息",
      "value": 132
    }, {
      "source": "Microsoft-Windows-NDIS",
      "target": "错误",
      "value": 1
    }, {
      "source": "Microsoft-Windows-Ntfs",
      "target": "信息",
      "value": 52
    }, {
      "source": "Microsoft-Windows-Power-Troubleshooter",
      "target": "信息",
      "value": 47
    }, {
      "source": "Microsoft-Windows-Security-Auditing",
      "target": "信息",
      "value": 10116
    }, {
      "source": "Microsoft-Windows-Security-SPP",
      "target": "信息",
      "value": 32
    }, {
      "source": "Microsoft-Windows-Security-SPP",
      "target": "警告",
      "value": 39
    }, {
      "source": "Microsoft-Windows-Sysmon",
      "target": "信息",
      "value": 772
    }, {
      "source": "Microsoft-Windows-TPM-WMI",
      "target": "信息",
      "value": 18
    }, {
      "source": "Microsoft-Windows-Time-Service",
      "target": "信息",
      "value": 74
    }, {
      "source": "Microsoft-Windows-Time-Service",
      "target": "警告",
      "value": 53
    }, {
      "source": "Microsoft-Windows-UserModePowerService",
      "target": "信息",
      "value": 36
    }, {
      "source": "Microsoft-Windows-UserPnp",
      "target": "信息",
      "value": 34
    }, {
      "source": "Microsoft-Windows-WLAN-AutoConfig",
      "target": "信息",
      "value": 23
    }, {
      "source": "Microsoft-Windows-WPDClassInstaller",
      "target": "信息",
      "value": 13
    }, {
      "source": "Microsoft-Windows-Windows Defender",
      "target": "信息",
      "value": 380
    }, {
      "source": "Microsoft-Windows-Windows Defender",
      "target": "警告",
      "value": 8
    }, {
      "source": "Microsoft-Windows-Windows Defender",
      "target": "错误",
      "value": 8
    }, {
      "source": "Microsoft-Windows-WindowsUpdateClient",
      "target": "信息",
      "value": 387
    }, {
      "source": "Microsoft-Windows-WindowsUpdateClient",
      "target": "错误",
      "value": 2
    }, {
      "source": "Microsoft-Windows-Wininit",
      "target": "信息",
      "value": 13
    }, {
      "source": "Microsoft-Windows-Winlogon",
      "target": "信息",
      "value": 29
    }, {
      "source": "MySQL",
      "target": "信息",
      "value": 7
    }, {
      "source": "SecurityCenter",
      "target": "信息",
      "value": 8
    }, {
      "source": "Service Control Manager",
      "target": "信息",
      "value": 135
    }, {
      "source": "Service Control Manager",
      "target": "错误",
      "value": 18
    }, {
      "source": "SpeechRuntime",
      "target": "信息",
      "value": 19
    }, {
      "source": "System Restore",
      "target": "信息",
      "value": 1
    }, {
      "source": "Tcpip",
      "target": "错误",
      "value": 7
    }, {
      "source": "User32",
      "target": "信息",
      "value": 10
    }, {
      "source": "VSS",
      "target": "信息",
      "value": 4
    }, {
      "source": "Virtual Disk Service",
      "target": "信息",
      "value": 1
    }, {
      "source": "Win32k",
      "target": "信息",
      "value": 34
    }, {
      "source": "Windows Error Reporting",
      "target": "信息",
      "value": 11
    }, {
      "source": "igfxCUIService2.0.0.0",
      "target": "Information",
      "value": 4
    }, {
      "source": ".NET Runtime",
      "target": "错误",
      "value": 2
    }, {
      "source": "AdobeARMservice",
      "target": "Information",
      "value": 8
    }, {
      "source": "Application Error",
      "target": "错误",
      "value": 4
    }, {
      "source": "BTHUSB",
      "target": "错误",
      "value": 16
    }, {
      "source": "Display",
      "target": "警告",
      "value": 1
    }, {
      "source": "ListenService",
      "target": "信息",
      "value": 12
    }]
  }
}
